name: wods_generator
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  freezed: ^2.4.5 # https://pub.dev/packages/freezed
  flutter_bloc: ^8.1.3 # https://pub.dev/packages/flutter_bloc
  freezed_annotation: ^2.4.1 # https://pub.dev/packages/freezed_annotation
  json_annotation: ^4.8.1 # https://pub.dev/packages/json_annotation
  http: ^1.1.0 # https://pub.dev/packages/http
  flutter_hooks: ^0.20.3 # https://pub.dev/packages/flutter_hooks
  stop_watch_timer: ^3.0.2 # https://pub.dev/packages/stop_watch_timer
  blinking_text: ^1.0.2 # https://pub.dev/packages/blinking_text
  bloc_test: ^9.1.4 # https://pub.dev/packages/bloc_test
  mocktail: ^1.0.1 # https://pub.dev/packages/mocktail

dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: ^6.7.1 # https://pub.dev/packages/json_serializable
  build_runner: ^2.4.6 # https://pub.dev/packages/build_runner
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # fonts
  fonts:
    - family: Korolev
      fonts:
        - asset: assets/fonts/korolev/korolev.otf